# Generated by Django 2.2 on 2020-08-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent', '0002_auto_20200815_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='v_news',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='v_overall',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='v_reddit',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='v_twitter',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
    ]
