# Generated by Django 2.2 on 2020-08-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent', '0003_auto_20200815_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='news',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='overall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='reddit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='twitter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='v_news',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='v_overall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='v_reddit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='v_twitter',
            field=models.FloatField(),
        ),
    ]
